### ISSUE TITLE
Entity()

### ISSUE THREAD

**Issue by RB-PRO** [dotnow/moysklad#2]
В примере есть код:
` productsWithParams := ms.Product().WithParams(p).Get()`
В реальности необходимо добавлять Entity().
`productsWithParams2 := ms.Entity().Product().WithParams(p).Get()`
С чем это связано?

**Comment by dotnow** [comment]
Это связано с тем, что README.md не обновлён. Я принял решение разделить вызовы на Entity(), Report() и Context().
Документацию обязательно дополню, но позже
