### ISSUE TITLE
Создание товара

### ISSUE THREAD

**Issue by RB-PRO** [dotnow/moysklad#3]
Здравствуйте! Спасибо за модуль для работы с API МойСклад. Очень интересная структура данных и вызовов функцией.
Именно по модели данных у меня возник вопрос, который, как я уверен, в дальнейшем поможет другим разработчикам быстро освоить данный модуль.
Как я могу создать [товар с дополнительными полями](https://dev.moysklad.ru/doc/api/remap/1.2/dictionaries/#suschnosti-towar-sozdat-towar)?
![image](https://user-images.githubusercontent.com/33092641/213192507-100bc55b-17ee-4b8f-84e4-f3a1e85e0152.png)

Заранее спасибо за ответ. С уважением! Роман.

**Comment by dotnow** [comment]
Благодарю за вопрос. Действительно, создание товара не очень ясное.
Постараюсь привести пример.

Для создания товара с доп полем нам необходимо заранее создать это самое доп поле.

Здесь мы создаём доп поле с двумя обязательными полями, отправляем запрос и выводим результат:
```
	attribute := entity.Attribute{
		Name: "Доп поле",
		Type: entity.AttributeTypeDouble,
	}

	result, response := ms.Entity().Product().CreateMetadataAttribute(attribute)
	if response.HasErrors() {
		log.Fatalln(response.GetErrors())
	}

	log.Println(result)
```
Если вы хотите сразу создать 2 и более доп полей - передаёте срез доп полей в метод 'BulkCreateOrUpdate'

В дальнейшем мы должны взять объект meta у того доп поля, с которым мы хотим создать товар и передать его с нужным значением.

Если у вас уже созданы доп поля, но вы не знаете их meta, то можно вытащить его по названию:
```
	attrName := "Доп поле 1" // Например, нам известно только название доп поля
	attrMeta := new(entity.Meta) // Сюда мы поместим meta от найденного доп поля

	// Получаем все доп поля сущности 'Товар'
	attributes, response := ms.Entity().Product().MetadataAttributes()
	if response.HasErrors() {
		log.Fatalln(response.GetErrors())
	}

	// Ищем поле по названию и узнаём его meta
	for _, attribute := range attributes.Rows {
		if attribute.Name == attrName {
			attrMeta = attribute.Meta
		}
	}

	// Создаём товар с единственным обязательным полем
	product := new(entity.Product)
	product.Name = "Яблоко"
	// Передаём meta и значение доп поля в срезе доп полей
	product.Attributes = []entity.Attribute{
		{
			Meta:  attrMeta,
			Value: 10,
		},
	}

	// Отправляем запрос за создание товара
	result, response := ms.Entity().Product().Create(product)
```

**Comment by RB-PRO** [comment]
Здравствуйте! Версия v0.0.2-beta2
Пытаюсь добавить цену товара, но к сожалению не получается. Привожу свой исходный код:

`
	// Создаём товар
	product := new(entity.Product)	currency, _ := ms.Entity().Currency().Get() // Получить информацию по валюте
	for _, val := range currency.Rows {         // Цикл по всем валютам
		if val.FullName == "Российский рубль" { // Если это рубль
			var price entity.FloatPrice                                       // Создаём объект цены
			price = 322.0                                                     // Устанавливаем цену
			product.BuyPrice = &entity.BuyPrice{Value: price, Currency: &val} // Закупочная цена items.Data[0].Price
		}
	}

	result, response := ms.Entity().Product().Create(*product)`

Товар добавляется, а вот цена, к сожалению нет. Быть может, что проблема со структурой entity.BuyPrice?

Ключ в json:
![image](https://user-images.githubusercontent.com/33092641/214122515-a068a2a6-12c9-4bba-8239-8e34d40acaff.png)
Ключ в документации:
![image](https://user-images.githubusercontent.com/33092641/214122643-85728767-0cf2-4bb3-9b42-2be245a87511.png)

Заранее спасибо за ответ. С уважением. Роман!

**Comment by dotnow** [comment]
Роман, всё верно. Благодарю!
Данное значение должно быть в нижнем регистре. Обновил до v0.0.2-beta3

К слову, модуль ждёт большой рефакторинг. При PUT/POST запросах в тело добавляется много лишней информации, которую мы явно не указываем, а это неправильно. Будут изменены все структуры. Цепочка вызовов останется той же, появятся методы Get() и Set() для всех полей

**Comment by RB-PRO** [comment]
Благодарю разработчика модуля и полностью поддерживаю нововведения, связанные с изменением структуры данных, добавлением методов Get() и Set(). Считаю, что такое решение можно будет назвать одной из вариаций best practice!
Рад, что лично повлиял на коммит v0.0.2-beta3.
Также для разработчиков, которые только начинают изучать данный модуль, могу порекомендовать ознакомиться с функцией комплексного добавления товара с картинкой, ценой и дополнительными полями.
https://github.com/RB-PRO/moysklad/blob/723c007fab4821d21330310b2e9aa4c7cee58ced/internal/app/AddProduct.go#L26

Огромное Вам Спасибо! Вы делаете благое дело для OpenSourse!
